name = "sol2"
main = "workers-site/index.js"
compatibility_date = "2025-05-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[site]
bucket = ".next"

[env.production]
name = "sol2"
